export const SPECIES = [
    { name: 'aarakocra' },
    { name: 'bugbear' },
    { name: 'centaur' },
    { name: 'dragonborn', subspecies: ['red', 'blue', 'white', 'green', 'black', 'silver', 'gold', 'bronze', 'copper', 'brass', 'amethyst', 'crystal quartz', 'emerald', 'sapphire', 'topaz'] },
    { name: 'duergar' },
    { name: 'dwarf', subspecies: ['hill', 'mountain'] },
    { name: 'eladrin', subspecies: ['winter', 'summer', 'spring', 'autumn'] },
    { name: 'elf', subspecies: ['dark', 'pallid', 'wood', 'high', 'crick'] },
    { name: 'fairy' },
    { name: 'firbolg' },
    { name: 'gnome', subspecies: ['forest', 'rock'] },
    { name: 'goblin' },
    { name: 'goliath' },
    { name: 'grung' },
    { name: 'half-elf' },
    { name: 'half-orc' },
    { name: 'halfling', subspecies: ['lightfoot', 'stout', 'ghostwise', 'lotusden']},
    { name: 'harengon' },
    { name: 'hobgoblin' },
    { name: 'human' },
    { name: 'kenku' },
    { name: 'kobold', subspecies: ['red', 'blue', 'white', 'green', 'black', 'silver', 'gold', 'bronze', 'copper', 'brass'] },
    { name: 'lizardfolk' },
    { name: 'minotaur' },
    { name: 'orc' },
    { name: 'owlin' },
    { name: 'satyr' },
    { name: 'tabaxi' },
    { name: 'tortle' },
    { name: 'triton' },
    { name: 'yuan-ti' },
    { name: 'sea elf' },
    { name: 'warforged', subspecies: ['envoy', 'juggernaut', 'skirmisher'] },
];

export const VARIANTS = [
    { name: 'genasi', subvariants: ['water', 'air', 'fire', 'earth', 'wood', 'metal'] },
    { name: 'aasimar', subvariants: ['protector', 'scourge', 'fallen'] },
    { name: 'tiefling', subvariants: ['baalzebub', 'dispater', 'fierna', 'glasya', 'levistus', 'mammon', 'mephistocles', 'zariel'] },
];

export const WEAPONS = [
    'axe',
    'club',
    'crossbow',
    'dagger',
    'dart',
    'glaive',
    'greatsword',
    'halberd',
    'handaxe',
    'knuckledusters',
    'light hammer',
    'light pick',
    'longbow',
    'mace',
    'pickaxe',
    'quarterstaff',
    'rapier',
    'scimitar',
    'scythe',
    'shortbow',
    'shortsword',
    'sickle',
    'sling',
    'spear',
    'spiked shield',
    'throwing knives',
    'tonfa',
    'torch and oil',
    'unarmed',
    'warhammer',
    'whip',
    'boomerang',
    'darts',
    'bolas',
    'maul',
    'gauntlets',
    'rock in a sock',
    'brick',
    'bottle of acid',
    'rope net',
    'ink pen',
    'wooden chair',
    'cooking pot',
    'large spoon',
    'bottle of ground pepper',
    'jar of bees',
    'holy water',
    'empty glass bottle',
    'wooden plank with nail',
    'pitchfork',
    'shovel',
    'claw hammer',
    'tongs',
    'garden shears',
    'trowel',
    'brick on a rope',
    'walking stick',
    'the nearest rock',
    'bottle of liquor'
]

export const MAGIC_TYPES = [
    'abjuration',
    'animating',
    'bear',
    'beast',
    'bird',
    'blood',
    'bone',
    'bubble',
    'charm',
    'clay',
    'cloud',
    'conifer',
    'copper',
    'divination',
    'duplication',
    'ember',
    'fire',
    'fish',
    'force',
    'fungus',
    'glass',
    'goat',
    'gold',
    'grapevine',
    'grass',
    'gravity',
    'healing',
    'ice',
    'illusion',
    'insect',
    'iron',
    'lake',
    'lava',
    'light',
    'lightning',
    'lunar',
    'magnetic',
    'memory',
    'mirror',
    'mud',
    'necromancy',
    'ocean',
    'octopus',
    'paper',
    'poison',
    'rain',
    'rat',
    'rune',
    'sand',
    'scent',
    'shadow',
    'silver',
    'smoke',
    'snow',
    'sound',
    'star',
    'steam',
    'stone',
    'time',
    'weather',
    'wind',
]

export const PROFESSIONS = [
    {name: 'acolyte', item: ''},
    {name: 'alchemist', item: ''},
    {name: 'apothecary', item: ''},
    {name: 'archaeologist', item: ''},
    {name: 'architect', item: ''},
    {name: 'armorer', item: ''},
    {name: 'author', item: ''},
    {name: 'baker', item: ''},
    {name: 'banker', item: ''},
    {name: 'barber', item: ''},
    {name: 'bartender', item: ''},
    {name: 'biologist', item: ''},
    {name: 'blacksmith', item: ''},
    {name: 'bookseller', item: ''},
    {name: 'bottlemaker', item: ''},
    {name: 'bounty hunter', item: ''},
    {name: 'brewer', item: ''},
    {name: 'bronzesmith', item: ''},
    {name: 'butcher', item: ''},
    {name: 'carpenter', item: ''},
    {name: 'carter/coachman', item: ''},
    {name: 'chandler', item: ''},
    {name: 'chef', item: ''},
    {name: 'cobbler', item: ''},
    {name: 'cooper', item: ''},
    {name: 'copyist', item: ''},
    {name: 'courier', item: ''},
    {name: 'embassador', item: ''},
    {name: 'farmer', item: ''},
    {name: 'ferry operator', item: ''},
    {name: 'falconer', item: ''},
    {name: 'beekeeper', item: ''},
    {name: 'maid', item: ''},
    {name: 'butler', item: ''},
    {name: 'fisher', item: ''},
    {name: 'fishmonger', item: ''},
    {name: 'fletcher', item: ''},
    {name: 'gardener', item: ''},
    {name: 'glassworker', item: ''},
    {name: 'goldsmith', item: ''},
    {name: 'guard', item: ''},
    {name: 'guide', item: ''},
    {name: 'hayward', item: ''},
    {name: 'herbalist', item: ''},
    {name: 'horsemonger', item: ''},
    {name: 'hunter(small game)', item: ''},
    {name: 'hunter(big game)', item: ''},
    {name: 'innkeeper', item: ''},
    {name: 'investigator', item: ''},
    {name: 'janitor', item: ''},
    {name: 'jeweler', item: ''},
    {name: 'journalist', item: ''},
    {name: 'knight', item: ''},
    {name: 'lamplighter', item: ''},
    {name: 'lawyer', item: ''},
    {name: 'leatherworker', item: ''},
    {name: 'librarian', item: ''},
    {name: 'limner', item: ''},
    {name: 'lockier', item: ''},
    {name: 'lumberjack', item: ''},
    {name: 'horsekeeper', item: ''},
    {name: 'mayor', item: ''},
    {name: 'merchant', item: ''},
    {name: 'messenger', item: ''},
    {name: 'miller', item: ''},
    {name: 'monk', item: ''},
    {name: 'musician', item: ''},
    {name: 'noble', item: ''},
    {name: 'notary', item: ''},
    {name: 'oatmonger', item: ''},
    {name: 'painter', item: ''},
    {name: 'plumber', item: ''},
    {name: 'potter', item: ''},
    {name: 'researcher', item: ''},
    {name: 'sailor', item: ''},
    {name: 'explorer', item: ''},
    {name: 'independently wealthy', item: ''},
    {name: 'retired', item: ''},
    {name: 'sawyer', item: 'handsaw'},
    {name: 'server(resturaunt)', item: ''},
    {name: 'shepherd', item: ''},
    {name: 'shipwright', item: ''},
    {name: 'shopkeeper', item: ''},
    {name: 'silversmith', item: ''},
    {name: 'smuggler', item: ''},
    {name: 'stonemason', item: ''},
    {name: 'tanner', item: ''},
    {name: 'taxcollector', item: ''},
    {name: 'teacher', item: ''},
    {name: 'tinsmith', item: ''},
    {name: 'translator', item: ''},
    {name: 'trapper', item: ''},
    {name: 'urchin', item: ''},
    {name: 'waste collector', item: ''},
    {name: 'weaver', item: ''},
    {name: 'wheelwright', item: ''},
    {name: 'woodsman', item: 'felling axe'},
];

// https://medievallondoners.ace.fordham.edu/occupations/