export const SPECIES = [
    { name: 'aarakocra' },
    { name: 'bugbear' },
    { name: 'centaur' },
    { name: 'dragonborn', subspecies: ['red', 'blue', 'white', 'green', 'black', 'silver', 'gold', 'bronze', 'copper', 'brass', 'amethyst', 'crystal quartz', 'emerald', 'sapphire', 'topaz'] },
    { name: 'duergar' },
    { name: 'dwarf', subspecies: ['hill', 'mountain'] },
    { name: 'eladrin', subspecies: ['winter', 'summer', 'spring', 'autumn'] },
    { name: 'elf', subspecies: ['dark', 'pallid', 'wood', 'high', 'crick'] },
    { name: 'fairy' },
    { name: 'firbolg' },
    { name: 'gnome', subspecies: ['forest', 'rock'] },
    { name: 'goblin' },
    { name: 'goliath' },
    { name: 'grung' },
    { name: 'half-elf' },
    { name: 'half-orc' },
    { name: 'halfling', subspecies: ['lightfoot', 'stout', 'ghostwise', 'lotusden']},
    { name: 'harengon' },
    { name: 'hobgoblin' },
    { name: 'human' },
    { name: 'kenku' },
    { name: 'kobold', subspecies: ['red', 'blue', 'white', 'green', 'black', 'silver', 'gold', 'bronze', 'copper', 'brass'] },
    { name: 'lizardfolk' },
    { name: 'minotaur' },
    { name: 'orc' },
    { name: 'owlin' },
    { name: 'satyr' },
    { name: 'tabaxi' },
    { name: 'tortle' },
    { name: 'triton' },
    { name: 'yuan-ti' },
    { name: 'sea elf' },
    { name: 'warforged', subspecies: ['envoy', 'juggernaut', 'skirmisher'] },
];

export const VARIANTS = [
    { name: 'genasi', subvariants: ['water', 'air', 'fire', 'earth', 'wood', 'metal'] },
    { name: 'aasimar', subvariants: ['protector', 'scourge', 'fallen'] },
    { name: 'tiefling', subvariants: ['baalzebub', 'dispater', 'fierna', 'glasya', 'levistus', 'mammon', 'mephistocles', 'zariel'] },
];

export const WEAPONS = [
    'axe',
    'club',
    'crossbow',
    'dagger',
    'dart',
    'glaive',
    'greatsword',
    'halberd',
    'handaxe',
    'knuckledusters',
    'light hammer',
    'light pick',
    'longbow',
    'mace',
    'pickaxe',
    'quarterstaff',
    'rapier',
    'scimitar',
    'scythe',
    'shortbow',
    'shortsword',
    'sickle',
    'sling',
    'spear',
    'spiked shield',
    'throwing knives',
    'tonfa',
    'torch and oil',
    'unarmed',
    'warhammer',
    'whip',
    'boomerang',
    'darts',
    'bolas',
    'maul',
    'gauntlets',
    'rock in a sock',
    'brick',
    'bottle of acid',
    'rope net',
    'ink pen',
    'wooden chair',
    'cooking pot',
    'large spoon',
    'bottle of ground pepper',
    'jar of bees',
    'holy water',
    'empty glass bottle',
    'wooden plank with nail',
    'pitchfork',
    'shovel',
    'claw hammer',
    'tongs',
    'garden shears',
    'trowel',
    'brick on a rope',
    'walking stick',
    'the nearest rock',
    'bottle of liquor'
]

export const MAGIC_TYPES = [
    'abjuration',
    'animating',
    'bear',
    'beast',
    'bird',
    'blood',
    'bone',
    'bubble',
    'charm',
    'clay',
    'cloud',
    'conifer',
    'copper',
    'divination',
    'duplication',
    'ember',
    'fire',
    'fish',
    'force',
    'fungus',
    'glass',
    'goat',
    'gold',
    'grapevine',
    'grass',
    'gravity',
    'healing',
    'ice',
    'illusion',
    'insect',
    'iron',
    'lake',
    'lava',
    'light',
    'lightning',
    'lunar',
    'magnetic',
    'memory',
    'mirror',
    'mud',
    'necromancy',
    'ocean',
    'octopus',
    'paper',
    'poison',
    'rain',
    'rat',
    'rune',
    'sand',
    'scent',
    'shadow',
    'silver',
    'smoke',
    'snow',
    'sound',
    'star',
    'steam',
    'stone',
    'time',
    'weather',
    'wind',
]

// may not have items when away from workplace
export const PROFESSIONS = [
    {name: 'acolyte', item: 'religious text, symbol of faith'},
    {name: 'alchemist', item: 'empty bottles, graduated cylinder, waterproof gloves'},
    {name: 'apothecary', item: 'mortar, pestle, herbs, textbook'},
    {name: 'archaeologist', item: 'notebook, pencil, sunhat, brush'},
    {name: 'architect', item: 'compass(drawing), pencil'},
    {name: 'armorer', item: 'leather awl, light hammer, oil, rag'},
    {name: 'author', item: 'notebook, pen'},
    {name: 'baker', item: 'apron, rolling pin'},
    {name: 'banker', item: 'abacus, identification, reading glasses'},
    {name: 'barber', item: 'straight razor, scissors, shaving cream, towel'},
    {name: 'bartender', item: ''},
    {name: 'biologist', item: ''},
    {name: 'blacksmith', item: 'long leather gloves, apron, hammer, tongs'},
    {name: 'bookseller', item: ''},
    {name: 'bottlemaker', item: ''},
    {name: 'bounty hunter', item: ''},
    {name: 'brewer', item: ''},
    {name: 'bronzesmith', item: ''},
    {name: 'butcher', item: 'cleaver, skinning knife, apron'},
    {name: 'carpenter', item: ''},
    {name: 'carter/coachman', item: ''},
    {name: 'chandler', item: ''},
    {name: 'chef', item: ''},
    {name: 'cobbler', item: ''},
    {name: 'cooper', item: ''},
    {name: 'copyist', item: ''},
    {name: 'courier', item: ''},
    {name: 'embassador', item: ''},
    {name: 'farmer', item: ''},
    {name: 'ferry operator', item: ''},
    {name: 'falconer', item: ''},
    {name: 'beekeeper', item: ''},
    {name: 'maid', item: ''},
    {name: 'butler', item: ''},
    {name: 'fisher', item: ''},
    {name: 'fishmonger', item: ''},
    {name: 'fletcher', item: ''},
    {name: 'gardener', item: ''},
    {name: 'glassworker', item: ''},
    {name: 'goldsmith', item: ''},
    {name: 'guard', item: ''},
    {name: 'guide', item: ''},
    {name: 'hayward', item: ''},
    {name: 'herbalist', item: ''},
    {name: 'horsemonger', item: ''},
    {name: 'hunter(small game)', item: ''},
    {name: 'hunter(big game)', item: ''},
    {name: 'innkeeper', item: ''},
    {name: 'investigator', item: ''},
    {name: 'janitor', item: ''},
    {name: 'jeweler', item: ''},
    {name: 'journalist', item: ''},
    {name: 'knight', item: ''},
    {name: 'lamplighter', item: ''},
    {name: 'lawyer', item: ''},
    {name: 'leatherworker', item: 'scrap leather, awl, knife, needle, thread'},
    {name: 'librarian', item: ''},
    {name: 'limner', item: 'pen, colored inks'},
    {name: 'lockier', item: ''},
    {name: 'lumberjack', item: 'axe'},
    {name: 'horsekeeper', item: 'bridle, treats, riding crop'},
    {name: 'mayor', item: ''},
    {name: 'merchant', item: 'abacus'},
    {name: 'messenger', item: ''},
    {name: 'miller', item: ''},
    {name: 'monk', item: ''},
    {name: 'musician', item: 'instrument, sheet music'},
    {name: 'noble', item: 'signet ring'},
    {name: 'notary', item: ''},
    {name: 'oatmonger', item: 'bags of different oat varieties'},
    {name: 'painter', item: 'paint, brush, pallet'},
    {name: 'plumber', item: ''},
    {name: 'potter', item: ''},
    {name: 'researcher', item: ''},
    {name: 'sailor', item: ''},
    {name: 'explorer', item: 'compass(magnetic)'},
    {name: 'independently wealthy', item: ''},
    {name: 'retired', item: 'deck of cards, smoking pipe'},
    {name: 'sawyer', item: 'handsaw, measuring tape'},
    {name: 'server(resturaunt)', item: 'petty cash, napkin'},
    {name: 'shepherd', item: 'hooked staff'},
    {name: 'shipwright', item: 'pencil, mallet, planer'},
    {name: 'shopkeeper', item: ''},
    {name: 'silversmith', item: 'jewelers loop, pliers'},
    {name: 'smuggler', item: ''},
    {name: 'stonemason', item: 'hammer and chisel'},
    {name: 'tanner', item: ''},
    {name: 'tax collector', item: ''},
    {name: 'teacher', item: ''},
    {name: 'tinsmith', item: 'tin snips'},
    {name: 'translator', item: ''},
    {name: 'trapper', item: 'bear trap'},
    {name: 'urchin', item: ''},
    {name: 'waste collector', item: ''},
    {name: 'weaver', item: 'woven backpack, reeds, shears'},
    {name: 'wheelwright', item: 'cord, clamp'},
    {name: 'woodsman', item: 'felling axe'},
];

// https://medievallondoners.ace.fordham.edu/occupations/