export const SPECIES = [
    { name: 'aarakocra' },
    { name: 'bugbear' },
    { name: 'centaur' },
    { name: 'dragonborn', subspecies: ['red', 'blue', 'white', 'green', 'black', 'silver', 'gold', 'bronze', 'copper', 'brass', 'amethyst', 'crystal quartz', 'emerald', 'sapphire', 'topaz'] },
    { name: 'duergar' },
    { name: 'dwarf', subspecies: ['hill', 'mountain'] },
    { name: 'eladrin', subspecies: ['winter', 'summer', 'spring', 'autumn'] },
    { name: 'elf', subspecies: ['dark', 'pallid', 'wood', 'high', 'crick'] },
    { name: 'fairy' },
    { name: 'firbolg' },
    { name: 'gnome', subspecies: ['forest', 'rock'] },
    { name: 'goblin' },
    { name: 'goliath' },
    { name: 'grung' },
    { name: 'half-elf' },
    { name: 'half-orc' },
    { name: 'halfling', subspecies: ['lightfoot', 'stout', 'ghostwise', 'lotusden']},
    { name: 'harengon' },
    { name: 'hobgoblin' },
    { name: 'human' },
    { name: 'kenku' },
    { name: 'kobold', subspecies: ['red', 'blue', 'white', 'green', 'black', 'silver', 'gold', 'bronze', 'copper', 'brass'] },
    { name: 'lizardfolk' },
    { name: 'minotaur' },
    { name: 'orc' },
    { name: 'owlin' },
    { name: 'satyr' },
    { name: 'tabaxi' },
    { name: 'tortle' },
    { name: 'triton' },
    { name: 'yuan-ti' },
    { name: 'sea elf' },
    { name: 'warforged', subspecies: ['envoy', 'juggernaut', 'skirmisher'] },
];

export const VARIANTS = [
    { 
        name: 'genasi',
        subvariants: [
            {name: 'water', link: 'https://dnd5e.wikidot.com/lineage:genasi-water'},
            {name: 'air', link: 'https://dnd5e.wikidot.com/lineage:genasi-air'},
            {name: 'fire', link: 'https://dnd5e.wikidot.com/lineage:genasi-fire'},
            {name: 'earth', link: 'https://dnd5e.wikidot.com/lineage:genasi-earth'}
        ]
    },
    {
        name: 'aasimar',
        subvariants:
        [
            {name: 'protector', link: 'https://dnd5e.wikidot.com/lineage:aasimar'},
            {name: 'scourge', link: 'https://dnd5e.wikidot.com/lineage:aasimar'},
            {name: 'fallen', link: 'https://dnd5e.wikidot.com/lineage:aasimar'}
        ]
    },
    {
        name: 'tiefling',
        subvariants: [
            {name: 'baalzebub', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
            {name: 'dispater', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
            {name: 'fierna', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
            {name: 'glasya', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
            {name: 'levistus', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
            {name: 'mammon', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
            {name: 'mephistocles', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
            {name: 'zariel', link: 'https://dnd5e.wikidot.com/lineage:tiefling'},
        ]
    },
];

export const WEAPONS = [
    'axe',
    'club',
    'crossbow',
    'dagger',
    'dart',
    'glaive',
    'greatsword',
    'halberd',
    'handaxe',
    'knuckledusters',
    'light hammer',
    'light pick',
    'longbow',
    'mace',
    'pickaxe',
    'quarterstaff',
    'rapier',
    'scimitar',
    'scythe',
    'shortbow',
    'shortsword',
    'sickle',
    'sling',
    'spear',
    'spiked shield',
    'throwing knives',
    'tonfa',
    'torch and oil',
    'unarmed, untrained',
    'unarmed, boxing',
    'unarmed, bar brawling',
    'unarmed, wrestling',
    'unarmed, karate',
    'unarmed, judo',
    'unarmed, bodybuilder',
    'warhammer',
    'whip',
    'boomerang',
    'darts',
    'bolas',
    'maul',
    'gauntlets',
    'rock in a sock',
    'brick',
    'vial of acid x3',
    'rope net',
    'ink pen',
    'wooden chair',
    'cooking pot',
    'jar of bees',
    'holy water',
    'empty glass bottle',
    'wooden plank with nail',
    'pitchfork',
    'shovel',
    'claw hammer',
    'tongs',
    'garden shears',
    'trowel',
    'brick on a rope',
    'walking stick',
    'a rock',
    'bottle of liquor'
]

export const MAGIC_TYPES = [
    'shield',
    'puppeteering',
    'bear',
    'beast',
    'bird',
    'blood',
    'bone',
    'bubble',
    'charm',
    'lucky charm',
    'writing',
    'clay',
    'cloud',
    'conifer',
    'copper',
    'divination',
    'duplication',
    'ember',
    'fire',
    'fish',
    'force',
    'fungus',
    'glass',
    'goat',
    'gold',
    'grapevine',
    'grass',
    'gravity',
    'healing',
    'ice',
    'illusion',
    'insect',
    'iron',
    'lake',
    'lava',
    'light',
    'lightning',
    'lunar',
    'magnetic',
    'memory',
    'mirror',
    'mud',
    'necromancy',
    'ocean',
    'octopus',
    'paper',
    'poison',
    'rain',
    'rat',
    'rune',
    'sand',
    'scent',
    'shadow',
    'silver',
    'smoke',
    'snow',
    'spirit',
    'silence',
    'music',
    'constellation',
    'steam',
    'stone',
    'time',
    'weather',
    'wind',
    'contract',
]

export const PROFESSIONS = [
    {name: 'acolyte', item: 'religious text, symbol of faith'},
    {name: 'alchemist', item: 'empty bottles, waterproof gloves'},
    {name: 'apothecary', item: 'herbs, textbook'},
    {name: 'archaeologist', item: 'notebook, pencil'},
    {name: 'architect', item: 'compass(drawing), pencil'},
    {name: 'armorer', item: 'light hammer, oil, rag'},
    {name: 'author', item: 'notebook, pen'},
    {name: 'baker', item: 'apron, rolling pin'},
    {name: 'banker', item: 'abacus, reading glasses'},
    {name: 'barber', item: 'straight razor, shaving cream'},
    {name: 'bartender', item: ''},
    {name: 'biologist', item: ''},
    {name: 'blacksmith', item: 'leather gloves, apron'},
    {name: 'bookseller', item: ''},
    {name: 'bottlemaker', item: ''},
    {name: 'bounty hunter', item: ''},
    {name: 'brewer', item: ''},
    {name: 'bronzesmith', item: ''},
    {name: 'butcher', item: 'skinning knife, apron'},
    {name: 'carpenter', item: ''},
    {name: 'carter/coachman', item: ''},
    {name: 'chandler', item: ''},
    {name: 'chef', item: ''},
    {name: 'cobbler', item: ''},
    {name: 'cooper', item: ''},
    {name: 'copyist', item: 'pen, ink'},
    {name: 'courier', item: ''},
    {name: 'embassador', item: ''},
    {name: 'farmer', item: ''},
    {name: 'ferry operator', item: 'pocket watch'},
    {name: 'falconer', item: ''},
    {name: 'beekeeper', item: 'beekeeper suit'},
    {name: 'maid', item: ''},
    {name: 'butler', item: ''},
    {name: 'fisher', item: ''},
    {name: 'fishmonger', item: ''},
    {name: 'fletcher', item: 'feathers'},
    {name: 'gardener', item: 'shears'},
    {name: 'glassworker', item: 'tinderbox'},
    {name: 'goldsmith', item: ''},
    {name: 'guard', item: ''},
    {name: 'guide', item: 'compass(magnetic), handdrawn map'},
    {name: 'hayward', item: ''},
    {name: 'herbalist', item: ''},
    {name: 'horsemonger', item: ''},
    {name: 'hunter(small game)', item: 'snare'},
    {name: 'hunter(big game)', item: ''},
    {name: 'innkeeper', item: ''},
    {name: 'investigator', item: ''},
    {name: 'janitor', item: ''},
    {name: 'jeweler', item: ''},
    {name: 'journalist', item: ''},
    {name: 'knight', item: ''},
    {name: 'lamplighter', item: ''},
    {name: 'lawyer', item: ''},
    {name: 'leatherworker', item: 'scrap leather, knife'},
    {name: 'librarian', item: ''},
    {name: 'limner', item: 'pen, colored inks'},
    {name: 'lockier', item: ''},
    {name: 'lumberjack', item: 'axe'},
    {name: 'horsekeeper', item: 'treats, riding crop'},
    {name: 'mayor', item: 'signet ring, sealing wax'},
    {name: 'merchant', item: 'abacus'},
    {name: 'messenger', item: 'sachel'},
    {name: 'miller', item: ''},
    {name: 'monk', item: ''},
    {name: 'musician', item: 'instrument, sheet music'},
    {name: 'noble', item: 'signet ring'},
    {name: 'notary', item: ''},
    {name: 'oatmonger', item: 'bags of different oat varieties'},
    {name: 'painter', item: 'paint, brush, pallet'},
    {name: 'plumber', item: ''},
    {name: 'potter', item: ''},
    {name: 'researcher', item: ''},
    {name: 'sailor', item: ''},
    {name: 'explorer', item: 'compass(magnetic)'},
    {name: 'independently wealthy', item: ''},
    {name: 'retired', item: 'deck of cards, smoking pipe'},
    {name: 'sawyer', item: 'handsaw, measuring tape'},
    {name: 'server(resturaunt)', item: 'petty cash'},
    {name: 'shepherd', item: 'hooked staff'},
    {name: 'shipwright', item: 'pencil, mallet'},
    {name: 'shopkeeper', item: ''},
    {name: 'silversmith', item: 'jewelers loop, pliers'},
    {name: 'smuggler', item: ''},
    {name: 'stonemason', item: 'light hammer, chisel'},
    {name: 'tanner', item: ''},
    {name: 'tax collector', item: ''},
    {name: 'teacher', item: 'chalk, treats'},
    {name: 'tinsmith', item: 'tin snips'},
    {name: 'translator', item: ''},
    {name: 'trapper', item: 'bear trap'},
    {name: 'urchin', item: ''},
    {name: 'waste collector', item: 'bandana'},
    {name: 'weaver', item: 'woven backpack, reeds, shears'},
    {name: 'wheelwright', item: 'cord, clamp'},
    {name: 'woodsman', item: 'felling axe'},
];

// https://medievallondoners.ace.fordham.edu/occupations/